### PR TITLE
Newsweek

### PR DESCRIPTION
**Pull request by jessicafarias**
This is a responsive website created with Bootstrap:
-The Bootstrap responsive grid system
-Pre-built buttons and navigation bar
-Flexbox utilities
-Text styles
-Sticky position for some sections.
-To hide and show sections according to the size of the screen.

The CSS file is used to put some background colors, text size, text color, and specific sizes for different elements.

#HEADER
The project includes 2 different headings.

#PRINCIPAL
The main includes all the different sections and each section contains all the related articles inside:
-Principal container (includes 3 columns and 5 sections)
-More stories section (only small devices)
-Subscribe container(only small devices)
-The U.S. section
-World section
-Business section
-Tech & Science section
-Culture section
-Sport section
-Subscribe  and newsletter section

#FOOTER
The footer includes the logo and some links.

### CODE REVIEW

**Comment by rammazzoti2000** [comment]
## Pull Request under review by Alexandru Bangau (TSE) :raised_hands:

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
### Hello @jessicafarias :raised_hands: I am Alexandru, the code reviewer for this project :smile: 
The project looks great and you have done wonderful job:
- [x] The Readme file is descriptive, as well the Pull Request summary
- [x] Commits are small and meaningful
- [x] You made good use of bootstrap classes, html is semantic and your css overall looks good
###
There are still some small issues to fix before approving this project though, follow the comments bellow :point_down: 
### :stop_sign: Required Changes :construction: :construction_worker_woman: 
### On large screens `(min-width: 992px)`
- [x] The `Heroes of Pandemic & Culture and Travel` sections should not have a hover effect and the font-size is too big, also some padding is missing between the picture and title description
### Clone:
image
### Original:
image
- [x] Here instead the `Editor's Pick` section is missing the hovering effect
### Clone:
image
### Original:
image
- [x] The `Subscribe & News` section should both vertically aligned see the bottom alignment between two
### Clone:
image
### Original:
image
### On medium screens `(min-width: 768px)`
- [x] The page presents some light horizontal overflow, I guess `overflow-x: hidden;` applied on <`html`> tag should fix it :point_down: 
image
- [x] This time the `Subscribe & News` section should instead align each on a new line
### Clone:
image
### 
image

- [x] The `social links` in the footer should be aligned to the right side, also make sure when the will align on the left side starting with small screens to have some padding on top 
### Clone:
image
### Orignal:
image
### On small screens `(min-width: 576px)`
- [x] The `Culture and Travel` section seems to lack some left margin / padding ? 
- [x] Between each article the page seems to lack some space
### Clone:
image
### Original:
image
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
### :stop_sign: Status: Required Changes

**Comment by jessicafarias** [comment]
Alexandru, thanks for the clear and helpful review.
The issues in the review now are already fixed, issues like the font sizes, hover effects, missing margin/ padding also the position for the footer for different sizes is fixed too.  
Thanks a lot!

**Review by sumancrest0001 — COMMENTED** [review]
**Status: Changes required
Hello @jessicafarias,**
You have done an awesome job to create a very similar layout to the original one. Break points are working smoothing and most of the issues addressed by the previous TSE are fixed. Thank you for that. I saw minor issues that need to be fixed before moving to the next project. Let's fix them.
[Required] Titles and images of US, culture, etc sections are not aligned properly. Currently, it looks like this :point_down: 
Screenshot from 2020-06-02 14-58-53

It should be like this :point_down: 
Screenshot from 2020-06-02 15-10-31

**Comment by sumancrest0001** [comment]
[Optional] on the small screen, sections are not aligned properly. left and right margins are different for different sections. I encourage you to fix this issues even though it is an optional change. Following images makes it clear :point_down: 
Screenshot from 2020-06-02 15-03-23


Screenshot from 2020-06-02 15-04-42

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Kindly make the above-requested changes and fill up another review form.**

If you have any queries regarding the review, feel free to message me on slack **Suman Shrestha**

**Happy coding !!!**

**Comment by jessicafarias** [comment]
Suman, thank you for your comments, now the text is now aligned, and all sections have the correct margin. 😃 
Regards!

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks:
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @jessicafarias! :+1:
- You can now merge to master. I wish you all the very best in your next tasks :first_place_medal:
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
